services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=vehiclesDB
      - POSTGRES_USER=vehiclesDB
      - POSTGRES_PASSWORD=root

volumes:
  postgres_data:
    driver: local
